# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pop3client_pb2 as pop3client__pb2


class MailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMailList = channel.unary_unary(
                '/MailService/GetMailList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pop3client__pb2.MailList.FromString,
                )
        self.GetMailPreviews = channel.unary_unary(
                '/MailService/GetMailPreviews',
                request_serializer=pop3client__pb2.MailPreviewRequest.SerializeToString,
                response_deserializer=pop3client__pb2.MailPreviewResponse.FromString,
                )
        self.UpdateMailList = channel.unary_unary(
                '/MailService/UpdateMailList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class MailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMailList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMailPreviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMailList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMailList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMailList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pop3client__pb2.MailList.SerializeToString,
            ),
            'GetMailPreviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMailPreviews,
                    request_deserializer=pop3client__pb2.MailPreviewRequest.FromString,
                    response_serializer=pop3client__pb2.MailPreviewResponse.SerializeToString,
            ),
            'UpdateMailList': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMailList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMailList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MailService/GetMailList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pop3client__pb2.MailList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMailPreviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MailService/GetMailPreviews',
            pop3client__pb2.MailPreviewRequest.SerializeToString,
            pop3client__pb2.MailPreviewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMailList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MailService/UpdateMailList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
