# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pop3client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pop3client.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10pop3client.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x95\x01\n\x0bMailPreview\x12\x0e\n\x06mailid\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x0c\n\x04uidl\x18\x03 \x01(\t\x12*\n\x07headers\x18\x04 \x03(\x0b\x32\x19.MailPreview.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"(\n\x08MailList\x12\x0e\n\x06length\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r\".\n\x12MailPreviewRequest\x12\x0b\n\x03pos\x18\x01 \x01(\r\x12\x0b\n\x03len\x18\x02 \x01(\r\"9\n\x13MailPreviewResponse\x12\"\n\x0cmail_preview\x18\x01 \x03(\x0b\x32\x0c.MailPreview2\xc5\x01\n\x0bMailService\x12\x32\n\x0bGetMailList\x12\x16.google.protobuf.Empty\x1a\t.MailList\"\x00\x12>\n\x0fGetMailPreviews\x12\x13.MailPreviewRequest\x1a\x14.MailPreviewResponse\"\x00\x12\x42\n\x0eUpdateMailList\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MAILPREVIEW_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='MailPreview.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MailPreview.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MailPreview.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=199,
)

_MAILPREVIEW = _descriptor.Descriptor(
  name='MailPreview',
  full_name='MailPreview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailid', full_name='MailPreview.mailid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='MailPreview.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uidl', full_name='MailPreview.uidl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='MailPreview.headers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAILPREVIEW_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=199,
)


_MAILLIST = _descriptor.Descriptor(
  name='MailList',
  full_name='MailList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='MailList.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='MailList.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=241,
)


_MAILPREVIEWREQUEST = _descriptor.Descriptor(
  name='MailPreviewRequest',
  full_name='MailPreviewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='MailPreviewRequest.pos', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='len', full_name='MailPreviewRequest.len', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=289,
)


_MAILPREVIEWRESPONSE = _descriptor.Descriptor(
  name='MailPreviewResponse',
  full_name='MailPreviewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mail_preview', full_name='MailPreviewResponse.mail_preview', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=348,
)

_MAILPREVIEW_HEADERSENTRY.containing_type = _MAILPREVIEW
_MAILPREVIEW.fields_by_name['headers'].message_type = _MAILPREVIEW_HEADERSENTRY
_MAILPREVIEWRESPONSE.fields_by_name['mail_preview'].message_type = _MAILPREVIEW
DESCRIPTOR.message_types_by_name['MailPreview'] = _MAILPREVIEW
DESCRIPTOR.message_types_by_name['MailList'] = _MAILLIST
DESCRIPTOR.message_types_by_name['MailPreviewRequest'] = _MAILPREVIEWREQUEST
DESCRIPTOR.message_types_by_name['MailPreviewResponse'] = _MAILPREVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MailPreview = _reflection.GeneratedProtocolMessageType('MailPreview', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAILPREVIEW_HEADERSENTRY,
    '__module__' : 'pop3client_pb2'
    # @@protoc_insertion_point(class_scope:MailPreview.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _MAILPREVIEW,
  '__module__' : 'pop3client_pb2'
  # @@protoc_insertion_point(class_scope:MailPreview)
  })
_sym_db.RegisterMessage(MailPreview)
_sym_db.RegisterMessage(MailPreview.HeadersEntry)

MailList = _reflection.GeneratedProtocolMessageType('MailList', (_message.Message,), {
  'DESCRIPTOR' : _MAILLIST,
  '__module__' : 'pop3client_pb2'
  # @@protoc_insertion_point(class_scope:MailList)
  })
_sym_db.RegisterMessage(MailList)

MailPreviewRequest = _reflection.GeneratedProtocolMessageType('MailPreviewRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAILPREVIEWREQUEST,
  '__module__' : 'pop3client_pb2'
  # @@protoc_insertion_point(class_scope:MailPreviewRequest)
  })
_sym_db.RegisterMessage(MailPreviewRequest)

MailPreviewResponse = _reflection.GeneratedProtocolMessageType('MailPreviewResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAILPREVIEWRESPONSE,
  '__module__' : 'pop3client_pb2'
  # @@protoc_insertion_point(class_scope:MailPreviewResponse)
  })
_sym_db.RegisterMessage(MailPreviewResponse)


_MAILPREVIEW_HEADERSENTRY._options = None

_MAILSERVICE = _descriptor.ServiceDescriptor(
  name='MailService',
  full_name='MailService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=351,
  serialized_end=548,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMailList',
    full_name='MailService.GetMailList',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_MAILLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMailPreviews',
    full_name='MailService.GetMailPreviews',
    index=1,
    containing_service=None,
    input_type=_MAILPREVIEWREQUEST,
    output_type=_MAILPREVIEWRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateMailList',
    full_name='MailService.UpdateMailList',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAILSERVICE)

DESCRIPTOR.services_by_name['MailService'] = _MAILSERVICE

# @@protoc_insertion_point(module_scope)
